settings:
  api:
    api_ip: '127.0.0.1'
    api_port: 8111
    indicators_endpoint: '/indicators'
    map_endpoint: '/map_info.json'
    air_info_endpoint: '/state'
  presence:
    show_indicators: False
    lang: en
    logo_theme: main_white